funding_types = [
    "Bright Futures",
    "Education Empowerment",
    "Scholarship Success",
    "Learning for All",
    "Future Leaders",
    "Knowledge Builders",
    "Opportunity Grants",
    "Academic Excellence",
    "Dreams to Reality",
    "Education Boost",
    "Inspire and Achieve",
    "Pathway to Success",
    "Empowering Education",
    "Building Bridges",
    "Educational Enrichment",
    "Supporting Scholars",
    "Investing in Minds",
    "Raising the Bar",
    "Creating Opportunities",
    "Education for All",
    "Success Scholars",
    "Mindful Education",
    "Making Dreams Come True",
    "Brighter Horizons",
    "Empowering Learners",
    "Future Innovators",
    "Educational Advancement",
    "Dream Big",
    "Nurturing Knowledge",
    "Inspiring Minds",
    "Unlocking Potential",
    "Igniting Intelligence",
    "Achievement Awards",
    "Building Brighter Futures",
    "Learning Enablers",
    "Scholarship Solutions",
    "Academic Support",
    "Investing in Education",
    "Future Visionaries",
    "Education for Tomorrow",
    "Enriching Lives",
    "Dream Chasers",
    "Pathways to Excellence",
    "Knowledge Empowerment",
    "Opportunity Seekers",
    "Inspiring Success",
    "Mindful Scholars",
    "Supporting Growth",
    "Breaking Barriers",
    "Education Boosters",
    "Empowering Dreams",
    "Builders of Tomorrow",
    "Unlocking Knowledge",
    "Mentorship Programs",
    "Empower and Excel",
    "Achievement Initiatives",
    "Success Builders",
    "Bright Minds",
    "Transforming Education",
    "Dreams Realized",
    "Scholarship Stars",
    "Academic Catalysts",
    "Investing in Potential",
    "Future Trailblazers",
    "Education Revolution",
    "Building Bridges to Success",
    "Learning Legacies",
    "Scholarship Success Stories",
    "Academic Empowerment",
    "Inspiration Nation",
    "Unlocking Success",
    "Dreams Unleashed",
    "Empowering Learners",
    "Creating Pathways",
    "Enriching Education",
    "Success Strategies",
    "Mindful Achievers",
    "Supporting Bright Minds",
    "Breaking Boundaries",
    "Education Elevators",
    "Dreams Fulfilled",
    "Scholarship Solutions",
    "Academic Allies",
    "Investing in Knowledge",
    "Future Pioneers",
    "Education Evolution",
    "Bright Beginnings",
    "Empowerment Zone",
    "Achievement Avenue",
    "Success Roadmap",
    "Knowledge Junction",
    "Dreamland Academy",
    "Pathway Partners",
    "Inspiring Education",
    "Unlocking Potential",
    "Dreams in Motion",
    "Empowering Futures",
    "Builders of Knowledge",
    "Nurturing Excellence",
    "Scholarship Seekers",
    "Academic Destiny",
    "Investing in Success",
    "Future Innovators",
    "Education Transformation",
    "Bright Stars",
    "Empowerment Catalysts",
    "Achievement Academy",
    "Success Springs",
    "Mindful Journey",
    "Supporting Dreams",
    "Breaking Barriers",
    "Education Champions",
    "Dreams Achieved",
]
