streets = [
    "Via Roma",
    "Corso Vittorio Emanuele II",
    "Via Cavour",
    "Via Mazzini",
    "Via Verdi",
    "Via Dante",
    "Corso Garibaldi",
    "Via Risorgimento",
    "Via Manzoni",
    "Via Umberto I",
    "Via Veneto",
    "Via San Francesco",
    "Via Marconi",
    "Corso Italia",
    "Via Pisa",
    "Via Milano",
    "Via Napoli",
    "Via Turati",
    "Via Genova",
    "Via Bologna",
    "Via Firenze",
    "Via Trento",
    "Via Siena",
    "Via Verona",
    "Via Venezia",
    "Via Trentino",
    "Via Palermo",
    "Via Modena",
    "Via Ferrara",
    "Via Padova",
    "Via Sicilia",
    "Via Calabria",
    "Via Toscana",
    "Via Lombardia",
    "Via Liguria",
    "Via Piemonte",
    "Via Umbria",
    "Via Sardegna",
    "Via Abruzzo",
    "Via Molise",
    "Via Lazio",
    "Via Veneto",
    "Via Friuli",
    "Via Emilia",
    "Via Romagna",
    "Via Marche",
    "Via Trastevere",
    "Via Appia",
    "Via Flaminia",
    "Via Cassia",
    "Via Salaria",
    "Via Nomentana",
    "Via Ostiense",
    "Via Aurelia",
    "Via Tuscolana",
    "Via Cola di Rienzo",
    "Via del Corso",
    "Via della Conciliazione",
    "Via del Babuino",
    "Via Vittoria",
    "Via Giulia",
    "Via Margutta",
    "Via dei Condotti",
    "Via Frattina",
    "Via Veneto",
    "Via del Tritone",
    "Via del Pellegrino",
    "Via di Ripetta",
    "Via Leonina",
    "Via del Boschetto",
    "Via Urbana",
    "Via Panisperna",
    "Via del Governo Vecchio",
    "Via di Monserrato",
    "Via Giulia",
    "Via dei Banchi Vecchi",
    "Via dei Coronari",
    "Via dei Leutari",
    "Via del Pellegrino",
    "Via di Panico",
    "Via della Lungara",
    "Via della Pilotta",
    "Via di Parione",
    "Via di Pasquino",
    "Via di Ponte Sisto",
    "Via Arenula",
    "Via dei Falegnami",
    "Via di Sant'Elena",
    "Via di Grotta Pinta",
    "Via dei Giubbonari",
    "Via dei Cappellari",
    "Via di Sant'Ambrogio",
    "Via dei Funari",
    "Via di Santa Maria in Monticelli",
    "Via del Portico d'Ottavia",
    "Via della Reginella",
    "Via in Publicolis",
    "Via del Progresso",
    "Via del Tempio",
    "Via in Piscinula",
    "Via dei Salumi",
    "Via dei Delfini",
    "Via dei Genovesi",
    "Via dei Sonnino",
    "Via dell'Arco de' Tolomei",
    "Via della Luce",
    "Via della Lungaretta",
    "Via di San Francesco a Ripa",
    "Via di Santa Cecilia",
    "Via di Sant'Egidio",
    "Via del Moro",
    "Via di San Calisto",
    "Via della Paglia",
    "Via dei Pettinari",
    "Via dei Savelli",
    "Via di Monte Fiore",
    "Via di Santo Stefano del Cacco",
    "Via di San Giovanni Decollato",
    "Via del Velabro",
    "Via di San Teodoro",
    "Via del Foro Piscario",
    "Via di Santa Prassede",
    "Via di San Martino ai Monti",
    "Via di Santa Pudenziana",
    "Via di San Pietro in Vincoli",
    "Via di Santa Maria Maggiore",
    "Via dei Serpenti",
    "Via Cavour",
    "Via dell'Olmata",
    "Via di Santa Maria ai Monti",
    "Via dei Capocci",
    "Via di San Francesco di Paola",
    "Via in Selci",
    "Via Giovanni Lanza",
    "Via Leonina",
    "Via Urbana",
    "Via degli Zingari",
    "Via del Boschetto",
    "Via Panisperna",
    "Via di San Martino ai Monti",
    "Via di Santa Prassede",
    "Via di San Pietro in Vincoli",
    "Via di Santa Maria Maggiore",
    "Via Merulana",
    "Via Mecenate",
    "Via di Sant'Agata dei Goti",
    "Via di Santa Bibiana",
    "Via di Porta San Lorenzo",
    "Via Marsala",
    "Via Cernaia",
    "Via Volturno",
    "Via Gaeta",
    "Via Solferino",
    "Via Castelfidardo",
    "Via Magenta",
    "Via Montebello",
    "Via Palestro",
    "Via dei Villini",
    "Via Nomentana",
    "Viale Regina Margherita",
    "Via Lamarmora",
    "Via Salaria",
    "Corso d'Italia",
    "Via Vittorio Veneto",
    "Via Bissolati",
    "Via Quintino Sella",
    "Via Sardegna",
    "Via Liguria",
    "Via Abruzzi",
    "Via Piemonte",
    "Via Marche",
    "Via Toscana",
    "Via Sicilia",
    "Via Campania",
    "Via Puglie",
    "Via Veneto",
    "Via Basilicata",
    "Via Calabria",
    "Via Molise",
    "Via Lombardia",
    "Via Emilia",
    "Via Romagna",
    "Via Friuli",
    "Via Lazio",
    "Via Trentino",
    "Via Piave",
    "Via Palestro",
    "Via Goito",
    "Via Pasquale Stanislao Mancini",
    "Via Montebello",
    "Via Magenta",
    "Via Varese",
    "Via Vittorio Bachelet",
    "Via Napoleone III",
    "Via Carlo Alberto",
    "Via Giovanni Amendola",
    "Via Principe Amedeo",
    "Via Cesare Balbo",
    "Via Cavour",
    "Via dei Serpenti",
    "Via Leonina",
    "Via degli Zingari",
    "Via del Cardello",
    "Via degli Ibernesi",
    "Via Baccina",
    "Via Tor de' Conti",
    "Via Madonna dei Monti",
    "Via della Polveriera",
    "Via dei Capocci",
    "Via dei Quattro Cantoni",
    "Via di Santa Maria Maggiore",
    "Via Merulana",
    "Via dell'Olmata",
    "Via Giovanni Lanza",
    "Via di San Martino ai Monti",
    "Via di Santa Prassede",
    "Via di San Pietro in Vincoli",
    "Via di Santa Maria Maggiore",
    "Via dei Serpenti",
    "Via Cavour",
    "Via degli Annibaldi",
    "Via Tor de' Conti",
    "Via Baccina",
    "Via dei Capocci",
    "Via dell'Olmata",
    "Via Giovanni Lanza",
    "Via di San Martino ai Monti",
    "Via di Santa Prassede",
    "Via di San Pietro in Vincoli",
    "Via di Santa Maria Maggiore",
    "Via Merulana",
    "Via Carlo Botta",
    "Via di Santa Maria Maggiore",
    "Via Mecenate",
    "Via di Santa Bibiana",
    "Via Giovanni Giolitti",
    "Via di Porta San Lorenzo",
    "Via Marsala",
    "Via Cernaia",
    "Via Solferino",
    "Via Gaeta",
    "Via Castelfidardo",
    "Via Volturno",
    "Via Goito",
    "Via XX Settembre",
    "Via Vittorio Emanuele Orlando",
    "Via dei Mille",
    "Via Antonio Salandra",
    "Via Firenze",
    "Via Sicilia",
    "Via Veneto",
    "Via Liguria",
    "Via Piemonte",
    "Via Campania",
    "Via Marche",
    "Via Abruzzi",
    "Via Toscana",
    "Via Sicilia",
    "Via Basilicata",
    "Via Calabria",
    "Via Molise",
    "Via Lombardia",
    "Via Emilia",
    "Via Romagna",
    "Via Friuli",
    "Via Lazio",
    "Via Trentino",
    "Via Piave",
    "Via Collina",
    "Via Vittorio Veneto",
    "Via di San Basilio",
    "Via Ludovisi",
    "Via Veneto",
    "Via Liguria",
    "Via Piemonte",
    "Via Campania",
    "Via Puglie",
    "Via Marche",
    "Via Abruzzi",
    "Via Toscana",
    "Via Sicilia",
    "Via Basilicata",
    "Via Calabria",
    "Via Molise",
    "Via Lombardia",
    "Via Emilia",
    "Via Romagna",
    "Via Friuli",
    "Via Lazio",
    "Via Trentino",
    "Via Piave",
    "Via Palestro",
    "Via Goito",
    "Via Pasquale Stanislao Mancini",
    "Via Montebello",
    "Via Magenta",
    "Via Varese",
    "Via Vittorio Bachelet",
    "Via Napoleone III",
    "Via Carlo Alberto",
    "Via Giovanni Amendola",
    "Via Principe Amedeo",
    "Via Cesare Balbo",
    "Via Cavour",
    "Via dei Serpenti",
    "Via Leonina",
    "Via degli Zingari",
    "Via del Cardello",
    "Via degli Ibernesi",
    "Via Baccina",
    "Via Tor de' Conti",
    "Via Madonna dei Monti",
    "Via della Polveriera",
    "Via dei Capocci",
    "Via dei Quattro Cantoni",
    "Via di Santa Maria Maggiore",
    "Via Merulana",
    "Via dell'Olmata",
    "Via Giovanni Lanza",
    "Via di San Martino ai Monti",
    "Via di Santa Prassede",
    "Via di San Pietro in Vincoli",
    "Via di Santa Maria Maggiore",
    "Via dei Serpenti",
    "Via Cavour",
    "Via degli Annibaldi",
    "Via Tor de' Conti",
    "Via Baccina",
    "Via dei Capocci",
    "Via dell'Olmata",
    "Via Giovanni Lanza",
    "Via di San Martino ai Monti",
    "Via di Santa Prassede",
    "Via di San Pietro in Vincoli",
    "Via di Santa Maria Maggiore",
    "Via Merulana",
    "Via Carlo Botta",
    "Via di Santa Maria Maggiore",
    "Via Mecenate",
    "Via di Santa Bibiana",
    "Via Giovanni Giolitti",
    "Via di Porta San Lorenzo",
    "Via Marsala",
    "Via Cernaia",
    "Via Solferino",
    "Via Gaeta",
    "Via Castelfidardo",
    "Via Volturno",
    "Via Goito",
    "Via XX Settembre",
    "Via Vittorio Emanuele Orlando",
    "Via dei Mille",
    "Via Antonio Salandra",
    "Via Firenze",
    "Via Sicilia",
    "Via Veneto",
    "Via Liguria",
    "Via Piemonte",
    "Via Campania",
    "Via Marche",
    "Via Abruzzi",
    "Via Toscana",
    "Via Sicilia",
    "Via Basilicata",
    "Via Calabria",
    "Via Molise",
    "Via Lombardia",
    "Via Emilia",
    "Via Romagna",
    "Via Friuli",
    "Via Lazio",
    "Via Trentino",
    "Via Piave",
    "Via Collina",
    "Via Vittorio Veneto",
    "Via di San Basilio",
    "Via Ludovisi",
    "Via Veneto",
    "Via Liguria",
    "Via Piemonte",
    "Via Campania",
    "Via Puglie",
    "Via Marche",
    "Via Abruzzi",
    "Via Toscana",
    "Via Sicilia",
    "Via Basilicata",
    "Via Calabria",
    "Via Molise",
    "Via Lombardia",
    "Via Emilia",
    "Via Romagna",
    "Via Friuli",
    "Via Lazio",
    "Via Trentino",
    "Via Piave",
]
