plants = {
    "Abies alba": "Silver Fir",
    "Acer campestre": "Field Maple",
    "Achillea millefolium": "Common Yarrow",
    "Adiantum capillus-veneris": "Maidenhair Fern",
    "Aesculus hippocastanum": "Horse Chestnut",
    "Agapanthus africanus": "African Lily",
    "Alcea rosea": "Hollyhock",
    "Allium sativum": "Garlic",
    "Alnus glutinosa": "Common Alder",
    "Aloe vera": "Aloe Vera",
    "Althaea officinalis": "Marshmallow",
    "Amaranthus retroflexus": "Redroot Amaranth",
    "Amaryllis belladonna": "Belladonna Lily",
    "Anacardium occidentale": "Cashew",
    "Anagallis arvensis": "Scarlet Pimpernel",
    "Anemone coronaria": "Poppy Anemone",
    "Angelica archangelica": "Angelica",
    "Anthriscus sylvestris": "Cow Parsley",
    "Aquilegia vulgaris": "Common Columbine",
    "Arachis hypogaea": "Peanut",
    "Arctium lappa": "Burdock",
    "Arctostaphylos uva-ursi": "Bearberry",
    "Argemone mexicana": "Mexican Prickly Poppy",
    "Armoracia rusticana": "Horseradish",
    "Artemisia absinthium": "Wormwood",
    "Arum maculatum": "Lords and Ladies",
    "Asparagus officinalis": "Asparagus",
    "Aspidistra elatior": "Cast Iron Plant",
    "Aster amellus": "European Michaelmas Daisy",
    "Astragalus membranaceus": "Milk Vetch",
    "Athrotaxis cupressoides": "Pencil Pine",
    "Athyrium filix-femina": "Lady Fern",
    "Atractylis gummifera": "Gum Dried Aristolochia",
    "Avena sativa": "Oat",
    "Azadirachta indica": "Neem",
    "Baptisia australis": "Blue False Indigo",
    "Barbarea vulgaris": "Common Winter Cress",
    "Begonia semperflorens": "Wax Begonia",
    "Bellis perennis": "Common Daisy",
    "Berberis vulgaris": "Common Barberry",
    "Beta vulgaris": "Beet",
    "Betula pendula": "Silver Birch",
    "Bidens pilosa": "Blackjack",
    "Bixa orellana": "Achiote",
    "Borago officinalis": "Borage",
    "Brassica oleracea": "Cabbage",
    "Bryonia dioica": "White Bryony",
    "Bupleurum fruticosum": "Shrubby Hare's-ear",
    "Butomus umbellatus": "Flowering Rush",
    "Cakile maritima": "Sea Rocket",
    "Calendula officinalis": "Marigold",
    "Callitriche stagnalis": "Water Starwort",
    "Calochortus luteus": "Yellow Mariposa Lily",
    "Camellia sinensis": "Tea",
    "Campanula medium": "Canterbury Bells",
    "Capsicum annuum": "Bell Pepper",
    "Cardamine pratensis": "Cuckoo Flower",
    "Carpobrotus edulis": "Hottentot Fig",
    "Carthamus tinctorius": "Safflower",
    "Carya illinoinensis": "Pecan",
    "Catharanthus roseus": "Madagascar Periwinkle",
    "Cedrus atlantica": "Atlas Cedar",
    "Celastrus orbiculatus": "Oriental Bittersweet",
    "Celtis australis": "European Hackberry",
    "Centaurea cyanus": "Cornflower",
    "Cephalotaxus harringtonii": "Japanese Plum Yew",
    "Ceratonia siliqua": "Carob",
    "Cercis siliquastrum": "Judas Tree",
    "Cichorium intybus": "Chicory",
    "Cirsium vulgare": "Bull Thistle",
    "Citrus aurantiifolia": "Lime",
    "Clematis vitalba": "Traveller's Joy",
    "Cnicus benedictus": "Blessed Thistle",
    "Colchicum autumnale": "Autumn Crocus",
    "Conium maculatum": "Poison Hemlock",
    "Convallaria majalis": "Lily of the Valley",
    "Cordyline australis": "Cabbage Tree",
    "Coreopsis tinctoria": "Plains Coreopsis",
    "Cornus sanguinea": "Dogwood",
    "Corylus avellana": "Hazelnut",
    "Cotinus coggygria": "Smoke Tree",
    "Crataegus monogyna": "Hawthorn",
    "Crocus sativus": "Saffron Crocus",
    "Cucumis sativus": "Cucumber",
    "Cucurbita pepo": "Pumpkin",
    "Cuscuta europaea": "European Dodder",
    "Cyclamen persicum": "Persian Cyclamen",
    "Cynara cardunculus": "Cardoon",
    "Cyperus papyrus": "Papyrus",
    "Dactylis glomerata": "Cocksfoot",
    "Dahlia pinnata": "Dahlia",
    "Datura stramonium": "Jimson Weed",
    "Digitalis purpurea": "Foxglove",
    "Diospyros kaki": "Persimmon",
    "Dipsacus fullonum": "Teasel",
    "Drosera rotundifolia": "Round-leaved Sundew",
    "Duchesnea indica": "Indian Strawberry",
    "Echium vulgare": "Viper's Bugloss",
    "Elaeagnus angustifolia": "Russian Olive",
    "Epilobium hirsutum": "Great Willowherb",
    "Equisetum arvense": "Field Horsetail",
    "Erica carnea": "Winter Heath",
    "Erigeron annuus": "Daisy Fleabane",
    "Eriobotrya japonica": "Loquat",
    "Eriophorum angustifolium": "Common Cottongrass",
    "Eucommia ulmoides": "Hardy Rubber Tree",
    "Eupatorium cannabinum": "Hemp Agrimony",
    "Euphorbia helioscopia": "Sun Spurge",
    "Fagus sylvatica": "European Beech",
    "Ferocactus cylindraceus": "California Barrel Cactus",
    "Festuca arundinacea": "Tall Fescue",
    "Ficus carica": "Common Fig",
    "Filipendula ulmaria": "Meadowsweet",
    "Foeniculum vulgare": "Fennel",
    "Fragaria vesca": "Wild Strawberry",
    "Fraxinus excelsior": "European Ash",
    "Fuchsia magellanica": "Hardy Fuchsia",
    "Gaillardia aristata": "Blanketflower",
    "Galanthus nivalis": "Snowdrop",
    "Gaultheria procumbens": "Wintergreen",
    "Gentiana acaulis": "Stemless Gentian",
    "Geranium maculatum": "Wild Geranium",
    "Geum urbanum": "Wood Avens",
    "Ginkgo biloba": "Ginkgo",
    "Glaucium flavum": "Yellow Horned Poppy",
    "Glechoma hederacea": "Ground Ivy",
    "Gleditsia triacanthos": "Honey Locust",
    "Glycyrrhiza glabra": "Liquorice",
    "Gossypium hirsutum": "Upland Cotton",
    "Gypsophila paniculata": "Baby's Breath",
    "Hamamelis virginiana": "Witch Hazel",
    "Hedera helix": "English Ivy",
    "Helianthus annuus": "Sunflower",
    "Helichrysum italicum": "Curry Plant",
    "Helleborus niger": "Christmas Rose",
    "Hemerocallis fulva": "Orange Daylily",
    "Hepatica nobilis": "Liverwort",
    "Heracleum sphondylium": "Hogweed",
    "Hibiscus rosa-sinensis": "Rose of China",
    "Hippeastrum hybridum": "Amaryllis",
    "Humulus lupulus": "Common Hop",
    "Hyacinthoides non-scripta": "Bluebell",
    "Hydrangea macrophylla": "Bigleaf Hydrangea",
    "Hypericum perforatum": "St. John's Wort",
    "Hypoestes phyllostachya": "Polka Dot Plant",
    "Ilex aquifolium": "Holly",
    "Impatiens walleriana": "Busy Lizzie",
    "Inula helenium": "Elecampane",
    "Ipomoea batatas": "Sweet Potato",
    "Iris germanica": "Bearded Iris",
    "Isatis tinctoria": "Woad",
    "Jasminum officinale": "Common Jasmine",
    "Juglans regia": "Common Walnut",
    "Juniperus communis": "Common Juniper",
    "Kalmia latifolia": "Mountain Laurel",
    "Knautia arvensis": "Field Scabious",
    "Kolkwitzia amabilis": "Beautybush",
    "Lactuca sativa": "Lettuce",
    "Lamium album": "White Dead Nettle",
    "Lantana camara": "Lantana",
    "Lathyrus odoratus": "Sweet Pea",
    "Laurus nobilis": "Bay Leaf",
    "Lavandula angustifolia": "Lavender",
    "Leontodon hispidus": "Rough Hawkbit",
    "Leucanthemum vulgare": "Oxeye Daisy",
    "Levisticum officinale": "Lovage",
    "Liatris spicata": "Blazing Star",
    "Lilium candidum": "Madonna Lily",
    "Limonium sinuatum": "Statice",
    "Linaria vulgaris": "Common Toadflax",
    "Linum usitatissimum": "Flax",
    "Liriodendron tulipifera": "Tulip Tree",
    "Lithodora diffusa": "Heavenly Blue",
    "Lobelia erinus": "Edging Lobelia",
    "Lonicera periclymenum": "Honeysuckle",
    "Lotus corniculatus": "Bird's-foot Trefoil",
    "Lunaria annua": "Honesty",
    "Lupinus polyphyllus": "Bigleaf Lupine",
    "Lycopersicon esculentum": "Tomato",
    "Lysimachia nummularia": "Creeping Jenny",
    "Macadamia integrifolia": "Macadamia Nut",
    "Magnolia grandiflora": "Southern Magnolia",
    "Malus domestica": "Apple",
    "Malva moschata": "Musk Mallow",
    "Marrubium vulgare": "White Horehound",
    "Matricaria chamomilla": "Chamomile",
    "Maurandya barclayana": "Climbing Snapdragon",
    "Medicago sativa": "Alfalfa",
    "Melaleuca alternifolia": "Tea Tree",
    "Melia azedarach": "Chinaberry",
    "Melilotus officinalis": "Yellow Sweet Clover",
    "Mentha piperita": "Peppermint",
    "Mimosa pudica": "Sensitive Plant",
    "Mirabilis jalapa": "Four O'Clock",
    "Morus nigra": "Black Mulberry",
    "Muscari armeniacum": "Grape Hyacinth",
    "Myosotis sylvatica": "Forget-Me-Not",
    "Myrtus communis": "Common Myrtle",
    "Narcissus poeticus": "Poet's Daffodil",
    "Nepeta cataria": "Catnip",
    "Nerium oleander": "Oleander",
    "Nicotiana tabacum": "Tobacco",
    "Nigella damascena": "Love-in-a-Mist",
    "Nymphaea odorata": "Fragrant Water Lily",
    "Ocimum basilicum": "Basil",
    "Oenothera biennis": "Evening Primrose",
    "Olea europaea": "Olive",
    "Ononis spinosa": "Restharrow",
    "Origanum vulgare": "Oregano",
    "Osmunda regalis": "Royal Fern",
    "Oxalis acetosella": "Wood Sorrel",
    "Paeonia lactiflora": "Peony",
    "Panicum virgatum": "Switchgrass",
    "Papaver orientale": "Oriental Poppy",
    "Parthenocissus quinquefolia": "Virginia Creeper",
    "Pastinaca sativa": "Parsnip",
    "Pelargonium graveolens": "Rose Geranium",
    "Pennisetum setaceum": "Purple Fountain Grass",
    "Penstemon digitalis": "Foxglove Beardtongue",
    "Peperomia obtusifolia": "Baby Rubber Plant",
    "Perovskia atriplicifolia": "Russian Sage",
    "Petunia x hybrida": "Petunia",
    "Phacelia tanacetifolia": "Purple Tansy",
    "Phalaris arundinacea": "Reed Canarygrass",
    "Phaseolus vulgaris": "Common Bean",
    "Phlox paniculata": "Garden Phlox",
    "Phyllostachys edulis": "Moso Bamboo",
    "Physalis peruviana": "Cape Gooseberry",
    "Picea abies": "Norway Spruce",
    "Pieris japonica": "Japanese Andromeda",
    "Pinus nigra": "Austrian Pine",
    "Pistacia vera": "Pistachio",
    "Plantago lanceolata": "Ribwort Plantain",
    "Platanus orientalis": "Oriental Plane",
    "Plumeria rubra": "Frangipani",
    "Podophyllum peltatum": "Mayapple",
    "Polygonatum biflorum": "Smooth Solomon's Seal",
    "Polystichum acrostichoides": "Christmas Fern",
    "Populus deltoides": "Eastern Cottonwood",
    "Portulaca oleracea": "Purslane",
    "Potentilla erecta": "Tormentil",
    "Primula vulgaris": "Primrose",
    "Prunella vulgaris": "Selfheal",
    "Prunus avium": "Sweet Cherry",
    "Prunus cerasifera": "Cherry Plum",
    "Prunus domestica": "European Plum",
    "Prunus dulcis": "Almond",
    "Prunus persica": "Peach",
    "Prunus serrulata": "Japanese Cherry",
    "Pseudotsuga menziesii": "Douglas Fir",
    "Ptelea trifoliata": "Waahoo",
    "Pteris cretica": "Cretan Brake",
    "Pulsatilla vulgaris": "Pasqueflower",
    "Punica granatum": "Pomegranate",
    "Pyrethrum cinerariifolium": "Dalmatian Chrysanthemum",
    "Pyrola rotundifolia": "Round-leaved Wintergreen",
    "Quercus cerris": "Turkey Oak",
    "Quercus ilex": "Holm Oak",
    "Quercus robur": "Common Oak",
    "Ranunculus acris": "Meadow Buttercup",
    "Raphanus sativus": "Radish",
    "Ratibida columnaris": "Mexican Hat",
    "Rehmannia glutinosa": "Chinese Foxglove",
    "Reseda odorata": "Mignonette",
    "Rhamnus cathartica": "Buckthorn",
    "Rheum rhabarbarum": "Rhubarb",
    "Rhododendron ponticum": "Rhododendron",
    "Ricinus communis": "Castor Oil Plant",
    "Robinia pseudoacacia": "Black Locust",
    "Rosa canina": "Dog Rose",
    "Rosmarinus officinalis": "Rosemary",
    "Rubus idaeus": "Raspberry",
    "Rudbeckia hirta": "Black-eyed Susan",
    "Rumex acetosa": "Common Sorrel",
    "Ruscus aculeatus": "Butcher's Broom",
    "Russelia equisetiformis": "Firecracker Plant",
    "Salix alba": "White Willow",
    "Salvia officinalis": "Common Sage",
    "Sambucus nigra": "Elderberry",
    "Sansevieria trifasciata": "Snake Plant",
    "Saponaria officinalis": "Soapwort",
    "Sarracenia purpurea": "Purple Pitcher Plant",
    "Satureja hortensis": "Summer Savory",
    "Saxifraga granulata": "Meadow Saxifrage",
    "Scabiosa columbaria": "Pincushion Flower",
    "Scilla siberica": "Siberian Squill",
    "Sedum acre": "Gold Moss",
    "Selaginella kraussiana": "Club Moss",
    "Senecio vulgaris": "Groundsel",
    "Sesamum indicum": "Sesame",
    "Sisyrinchium angustifolium": "Blue-eyed Grass",
    "Solanum dulcamara": "Bittersweet Nightshade",
    "Solanum lycopersicum": "Tomato",
    "Sorbus aucuparia": "Rowan",
    "Spartium junceum": "Spanish Broom",
    "Spiraea japonica": "Japanese Spiraea",
    "Stachys officinalis": "Betony",
    "Stellaria media": "Chickweed",
    "Strelitzia reginae": "Bird of Paradise",
    "Styrax japonicus": "Japanese Snowbell",
    "Tagetes erecta": "Marigold",
    "Taraxacum officinale": "Dandelion",
    "Taxus baccata": "Yew",
    "Teucrium chamaedrys": "Wall Germander",
    "Thuja occidentalis": "Northern White Cedar",
    "Thymus vulgaris": "Thyme",
    "Tilia cordata": "Small-leaved Lime",
    "Tithonia rotundifolia": "Mexican Sunflower",
    "Torenia fournieri": "Wishbone Flower",
    "Trachycarpus fortunei": "Chinese Windmill Palm",
    "Tradescantia zebrina": "Wandering Jew",
    "Tragopogon pratensis": "Goat's Beard",
    "Trifolium pratense": "Red Clover",
    "Triticum aestivum": "Wheat",
    "Tropaeolum majus": "Nasturtium",
    "Tsuga canadensis": "Eastern Hemlock",
    "Tulipa gesneriana": "Garden Tulip",
    "Ulmus glabra": "Wych Elm",
    "Urtica dioica": "Stinging Nettle",
    "Vaccinium corymbosum": "Highbush Blueberry",
    "Valeriana officinalis": "Valerian",
    "Verbascum blattaria": "Moth Mullein",
    "Verbena bonariensis": "Purpletop Vervain",
    "Vernonia gigantea": "Giant Ironweed",
    "Viburnum opulus": "European Cranberrybush",
    "Vinca minor": "Common Periwinkle",
    "Viola odorata": "Sweet Violet",
    "Viscum album": "Mistletoe",
    "Vitis vinifera": "Grape",
    "Wisteria sinensis": "Chinese Wisteria",
    "Xanthium strumarium": "Cocklebur",
    "Yucca filamentosa": "Adam's Needle",
    "Zantedeschia aethiopica": "Calla Lily",
    "Zea mays": "Corn",
    "Zinnia elegans": "Youth-and-old-age",
}
