schools: list[tuple[str, str]] = [
    ("Primaria", "Primaria"),
    ("Secondaria", "Secondaria di Primo Grado"),
    ("Liceo Classico", "Secondaria di Secondo Grado"),
    ("Liceo Scientifico", "Secondaria di Secondo Grado"),
    ("Liceo Linguistico", "Secondaria di Secondo Grado"),
    ("Liceo delle Scienze Umane", "Secondaria di Secondo Grado"),
    ("Liceo Artistico", "Secondaria di Secondo Grado"),
    ("Liceo Musicale e Coreutico", "Secondaria di Secondo Grado"),
    ("Istituto Tecnico Economico", "Secondaria di Secondo Grado"),
    ("Istituto Tecnico Tecnologico", "Secondaria di Secondo Grado"),
    ("Istituto Tecnico Agrario", "Secondaria di Secondo Grado"),
    ("Istituto Tecnico per il Turismo", "Secondaria di Secondo Grado"),
    ("Istituto Tecnico Industriale", "Secondaria di Secondo Grado"),
    ("Istituto Tecnico Commerciale", "Secondaria di Secondo Grado"),
    (
        "Istituto Professionale per i Servizi Alberghieri e della Ristorazione",
        "Secondaria di Secondo Grado",
    ),
    ("Istituto Professionale per l'Agricoltura", "Secondaria di Secondo Grado"),
    (
        "Istituto Professionale per l'Industria e l'Artigianato",
        "Secondaria di Secondo Grado",
    ),
    ("Istituto Professionale per i Servizi Commerciali", "Secondaria di Secondo Grado"),
    ("Istituto Professionale per i Servizi Sociali", "Secondaria di Secondo Grado"),
    ("Istituto Professionale per i Servizi Turistici", "Secondaria di Secondo Grado"),
    ("Facoltà di Economia", "Università"),
    ("Facoltà di Ingegneria", "Università"),
    ("Facoltà di Medicina e Chirurgia", "Università"),
    ("Facoltà di Scienze Matematiche, Fisiche e Naturali", "Università"),
    ("Facoltà di Lettere e Filosofia", "Università"),
    ("Facoltà di Psicologia", "Università"),
    ("Facoltà di Architettura", "Università"),
    ("Facoltà di Scienze Politiche", "Università"),
    ("Facoltà di Giurisprudenza", "Università"),
    ("Facoltà di Scienze dell'Educazione", "Università"),
    ("Facoltà di Scienze della Comunicazione", "Università"),
    ("Facoltà di Scienze Motorie", "Università"),
    ("Facoltà di Scienze Ambientali", "Università"),
    ("Facoltà di Scienze Agrarie", "Università"),
    ("Facoltà di Scienze della Formazione", "Università"),
    ("Facoltà di Scienze Biologiche", "Università"),
    ("Facoltà di Veterinaria", "Università"),
    ("Facoltà di Lingue e Letterature Straniere", "Università"),
    ("Facoltà di Sociologia", "Università"),
    ("Facoltà di Statistica", "Università"),
    ("Facoltà di Farmacia", "Università"),
    ("Facoltà di Odontoiatria", "Università"),
    ("Facoltà di Conservazione dei Beni Culturali", "Università"),
    ("Facoltà di Musicologia", "Università"),
    ("Facoltà di Scienze e Tecnologie Alimentari", "Università"),
    ("Facoltà di Urbanistica", "Università"),
    ("Facoltà di Design e Arti", "Università"),
    ("Facoltà di Scienze Astronomiche", "Università"),
    ("Facoltà di Scienze Geologiche", "Università"),
    ("Facoltà di Chimica Industriale", "Università"),
    ("Facoltà di Matematica", "Università"),
    ("Facoltà di Fisica", "Università"),
    ("Facoltà di Scienze della Terra", "Università"),
    ("Facoltà di Informatica", "Università"),
    ("Facoltà di Biotecnologie", "Università"),
    ("Facoltà di Scienze Marittime e Navali", "Università"),
    ("Facoltà di Scienze della Nutrizione Umana", "Università"),
    ("Facoltà di Scienze Forensi", "Università"),
    ("Facoltà di Statistica Demografica e Attuariale", "Università"),
    ("Facoltà di Biochimica", "Università"),
    ("Facoltà di Antichità e Belle Arti", "Università"),
    ("Facoltà di Pedagogia", "Università"),
    ("Facoltà di Scienze della Traduzione e dell'Interpretazione", "Università"),
    ("Facoltà di Interpretariato e Traduzione", "Università"),
    ("Facoltà di Scienze del Turismo", "Università"),
    ("Facoltà di Scienze Cognitive", "Università"),
    ("Facoltà di Archeologia", "Università"),
    ("Facoltà di Filologia Moderna", "Università"),
    ("Facoltà di Storia dell'Arte", "Università"),
    ("Facoltà di Scienze del Patrimonio Culturale", "Università"),
    ("Facoltà di Filosofia e Storia della Filosofia", "Università"),
    ("Facoltà di Studi Orientali", "Università"),
    ("Facoltà di Scienze Politiche e Sociali", "Università"),
    ("Facoltà di Scienze Religiose", "Università"),
    ("Facoltà di Studi Interculturali", "Università"),
    ("Facoltà di Scienze della Mediazione Linguistica", "Università"),
    ("Facoltà di Scienze del Teatro e dello Spettacolo", "Università"),
    ("Facoltà di Scienze e Tecniche Psicologiche", "Università"),
    ("Facoltà di Bioingegneria", "Università"),
    ("Facoltà di Ingegneria Aerospaziale", "Università"),
    ("Facoltà di Ingegneria Biomedica", "Università"),
    ("Facoltà di Ingegneria Chimica", "Università"),
    ("Facoltà di Ingegneria Civile", "Università"),
    ("Facoltà di Ingegneria Elettronica", "Università"),
    ("Facoltà di Ingegneria Energetica", "Università"),
    ("Facoltà di Ingegneria Gestionale", "Università"),
    ("Facoltà di Ingegneria dei Materiali", "Università"),
    ("Facoltà di Ingegneria delle Telecomunicazioni", "Università"),
    ("Facoltà di Ingegneria Informatica", "Università"),
    ("Facoltà di Ingegneria Meccanica", "Università"),
    ("Facoltà di Ingegneria Navale", "Università"),
]
