sensors = [
    "Temperature",
    "Humidity",
    "Light",
    "Soil Moisture",
    "CO2",
    "Air Quality",
    "Rainfall",
    "Wind Speed",
    "Wind Direction",
    "UV Index",
    "pH",
    "Nutrient",
    "Water Level",
    "Leaf Wetness",
    "Atmospheric Pressure",
    "Solar Radiation",
    "Anemometer",
    "Barometer",
    "Thermometer",
    "Hygrometer",
    "Photometer",
    "Pyranometer",
    "Lux Meter",
    "Leaf Area Meter",
    "Evapotranspiration",
    "Growth Rate",
    "Leaf Chlorophyll",
    "Leaf Conductance",
    "Leaf Expansion",
    "Leaf Angle",
    "Leaf Color",
    "Fruit Ripeness",
    "Root Zone Moisture",
    "Stem Diameter",
    "Bark Thickness",
    "Vibration",
    "Noise Level",
    "Infrared Thermometer",
    "Ultrasonic Distance",
    "Water pH",
    "Water Conductivity",
    "Water Turbidity",
    "Water Dissolved Oxygen",
    "Water Flow",
    "Water Pressure",
    "Water Salinity",
    "Water Depth",
    "Leaf Temperature",
    "Insect Population",
    "Leaf Disease",
    "Pollination",
    "Ozone",
    "Carbon Monoxide",
    "Ammonia",
    "Nitrogen Dioxide",
    "Sulfur Dioxide",
    "Methane",
    "Ethylene",
    "Plant Growth Regulator",
    "Insect Pheromone",
    "Plant Pathogen",
    "Pollutant Particulate",
    "Fertilizer Injector",
    "Nutrient Dosing",
    "CO2 Injection",
    "Irrigation System",
    "Water Pump",
    "Water Filtration",
    "Misting System",
    "Shade Cloth",
]
